### ISSUE TITLE
Least functionality release

### ISSUE THREAD

**Issue by slhmy** [OJ-lab/roadmap#1]
This is a conclusion issue for the "Least functionality release" Milestone.
**Which includes a list of targets to make OJ Lab complete with the basic functionality of a traditional Online Judge Platform.**

For Judger we got a implemented core functionality, but a CLI is still needed. This is mainly for getting a easier way to start Judger everywhere including in Dev situation.

For Platform (the core service) we need to finish the implementation of  Submission data object which shows a good and clear result of the judge.
User register and role control should also be considered.

For the frontend, UI perf is the main part. Data should be gracefully processed after Platform implementation.

Finally we should build a brief knowledge map of the whole technical skill we used in OJ Lab, this is mainly for helping new comers to quickly learn how to join OJ Lab. However these knowledge can be also very useful when we go on to other projects.

The following is the total task list, I have not finished it.

#### Judger and Task

A reliable and clear judge/submission queue is needed.

- [x] OJ-lab/oj-lab-services#29
- [ ] OJ-lab/judger#30
  - [ ] OJ-lab/judger#80
  - [ ] OJ-lab/judger#107

#### Frontend

- [ ] OJ-lab/oj-lab-front#27
- [ ] OJ-lab/oj-lab-front#10
- [ ] OJ-lab/oj-lab-front#13
- [ ] OJ-lab/oj-lab-front#28

**Comment by Plalyy** [comment]
I think we can set some milestones that are more specific.
For example, least functionality release(mvp) includes basic functions such as basic Oj interaction and available judgment queues ( v0.1, v0.2, ... ).
The poc version should include more comprehensive content, such as user management as mentioned by the supervisor @slhmy , etc. It can be split more specifically according to functional stages ( v1.0, v1.1, ... ).

I think that It's necessary to determine which version can be launched online, and we can do more interesting work base on the version. It's more visible.
More needs to be discussed.

@slhmy @KanadeSiina @Zztrans @sirius2alpha
